os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=6.11.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - chmod +x mvnw
  - ./mvnw clean test
  - yarn test
  - ./mvnw package -Pprod -DskipTests
  - sonar-scanner
addons:
  sonarcloud:
    organization: "sandervanloock-github"
    token:
      secure: "mxiE6jqDZmjTMBYIQTR6foDO/I6idEJJhNwL3kkDKQJ1d2Y5P1OkHK4AqCVrJyBOIePHH/oMXTxtSJyoVz/ebUwxNpbJNH9VjlJCUmIQmKvNr24zlk6psNGug5tC3ioiNAo4qouHhsvSXK6OS+pv9MIjIwO+6h07z2fIqWcTZ4Jxc7uAf4L/o8NBeGDrbCyXxhrsm9UyFR+NBkuxU9mAsJAAgqJXM9udUAx4U6PWsmd3Cel0L0YgYMjk11l2BbqwRqvGx32ZMhbJLDomkxb7sQtACSN9jJSrnVaoIkcImEX2HlI7gmRopUu6F7ifISuFSohefvCHTGP94LjQEXtVbja3qVcOkA3AA3Ls3rtV2cJY7WbqE8iNcI7a/T8GYac9dkwWyYzxqg5EWgfQb3Q8fklvKN0GooFvWn+acpVrQ0/50TocZerLBddrNEBWHXdZ9ANuJRpzjDdolPPUUVqymmUzN24b/ncFTaB6tn8POG0W9u4u5ehdgHDyo5QlJkRkk              SKhxYaTzCFYnCzLKuDPjZiEzqfJ4xeFFhrIrIjLnBJgy6GJD23AK8znF5cSHmMp2jv8sBt/kMF3YzWUAUaE5mYR3o1I+uHsZpmi6g1/1hsS4V1/WidUCPe3k0A31wDBAhsPQf5oxFV48QUHsqJwlnetrDPB/QcyIaXpeN685QQ="
