version: '2'
services:
    websiteindexer-app:
        image: websiteindexer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://websiteindexer-mysql:3306/websiteindexer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    websiteindexer-mysql:
        extends:
            file: mysql.yml
            service: websiteindexer-mysql
